# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghp < Formula
  desc "Github Proxy | Github 代理"
  homepage "https://blog.gclmit.club"
  version "1.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gclm/ghp/releases/download/v1.0.4/ghp_1.0.4_darwin_arm64.tar.gz"
      sha256 "207573bd4e01183bc62e4a048b73afea83a2b7e3a2cfa2b9bc4230ee84e14db1"

      def install
        bin.install "ghp"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "bash")
        (bash_completion/"ghp").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "zsh")
        (zsh_completion/"_ghp").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gclm/ghp/releases/download/v1.0.4/ghp_1.0.4_darwin_amd64.tar.gz"
      sha256 "279f6f81895b72cd86189cdf90b93f5e0f060f03f123cf9b2a1b08a2fa669484"

      def install
        bin.install "ghp"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "bash")
        (bash_completion/"ghp").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "zsh")
        (zsh_completion/"_ghp").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gclm/ghp/releases/download/v1.0.4/ghp_1.0.4_linux_arm64.tar.gz"
      sha256 "6790a86904e8693b1667098a34c78b147397812ae6df58f603b56af2ffa88580"

      def install
        bin.install "ghp"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "bash")
        (bash_completion/"ghp").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "zsh")
        (zsh_completion/"_ghp").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gclm/ghp/releases/download/v1.0.4/ghp_1.0.4_linux_amd64.tar.gz"
      sha256 "8b58f7cc668ad90e2d7394f7b69608db991bdd9719ecdee1f627b8876de025d3"

      def install
        bin.install "ghp"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "bash")
        (bash_completion/"ghp").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "zsh")
        (zsh_completion/"_ghp").write output
      end
    end
  end

  depends_on "git"

  test do
    system "#{bin}/ghp curl https://raw.githubusercontent.com/gclm/homebrew-tap/note/README.md"
  end
end
