# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghp < Formula
  desc "Github Proxy | Github 代理"
  homepage "https://blog.gclmit.club"
  version "1.0.3-rc4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gclm/ghp/releases/download/v1.0.3-rc4/ghp_1.0.3-rc4_darwin_amd64.tar.gz"
      sha256 "acc5f4893f4597f5e02caab07763f758673639187c4c7b2b7990f0937756707f"

      def install
        bin.install "ghp"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "bash")
        (bash_completion/"ghp").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "zsh")
        (zsh_completion/"_ghp").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gclm/ghp/releases/download/v1.0.3-rc4/ghp_1.0.3-rc4_darwin_arm64.tar.gz"
      sha256 "31f46b86e6d6bfa83acc3f9f50c4f2f669dec8b136cf5eb7300149754e7d737e"

      def install
        bin.install "ghp"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "bash")
        (bash_completion/"ghp").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "zsh")
        (zsh_completion/"_ghp").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gclm/ghp/releases/download/v1.0.3-rc4/ghp_1.0.3-rc4_linux_arm64.tar.gz"
      sha256 "a789d916f9ed1971ba6b49d3d0cea056aae151b2a82e5254ef119fbd48c50511"

      def install
        bin.install "ghp"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "bash")
        (bash_completion/"ghp").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "zsh")
        (zsh_completion/"_ghp").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gclm/ghp/releases/download/v1.0.3-rc4/ghp_1.0.3-rc4_linux_amd64.tar.gz"
      sha256 "f6e9f4ed0340434decd6b5e94395178868b325818a45100fe136e147535cb349"

      def install
        bin.install "ghp"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "bash")
        (bash_completion/"ghp").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "zsh")
        (zsh_completion/"_ghp").write output
      end
    end
  end

  depends_on "git"

  test do
    system "#{bin}/ghp curl https://raw.githubusercontent.com/gclm/homebrew-tap/note/README.md"
  end
end
