# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghp < Formula
  desc "Github Proxy | Github 代理"
  homepage "https://blog.gclmit.club"
  version "1.0.4-beta1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gclm/ghp/releases/download/v1.0.4-beta1/ghp_1.0.4-beta1_darwin_amd64.tar.gz"
      sha256 "8bbb21fcd63c7b6a006176e61d03c5c4560e3371f3a993aa6db3efdf750aac31"

      def install
        bin.install "ghp"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "bash")
        (bash_completion/"ghp").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "zsh")
        (zsh_completion/"_ghp").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gclm/ghp/releases/download/v1.0.4-beta1/ghp_1.0.4-beta1_darwin_arm64.tar.gz"
      sha256 "c74790d38429f78ba656ff00e16a5b6abeb3593ee21fd166267b963b9eebf911"

      def install
        bin.install "ghp"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "bash")
        (bash_completion/"ghp").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "zsh")
        (zsh_completion/"_ghp").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gclm/ghp/releases/download/v1.0.4-beta1/ghp_1.0.4-beta1_linux_arm64.tar.gz"
      sha256 "b4fe09d0232139950c71bef81d3bf4e080c572c97f595834a50b70fbb19a104c"

      def install
        bin.install "ghp"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "bash")
        (bash_completion/"ghp").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "zsh")
        (zsh_completion/"_ghp").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gclm/ghp/releases/download/v1.0.4-beta1/ghp_1.0.4-beta1_linux_amd64.tar.gz"
      sha256 "21007357cdab543699365dee31bd20f2bcd9c6fd9979a7a9db9a41b60996f8b1"

      def install
        bin.install "ghp"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "bash")
        (bash_completion/"ghp").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/ghp", "completion", "zsh")
        (zsh_completion/"_ghp").write output
      end
    end
  end

  depends_on "git"

  test do
    system "#{bin}/ghp curl https://raw.githubusercontent.com/gclm/homebrew-tap/note/README.md"
  end
end
